/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_danoeh_antennapod_bittorrent_TorrentHandle */

#ifndef _Included_de_danoeh_antennapod_bittorrent_TorrentHandle
#define _Included_de_danoeh_antennapod_bittorrent_TorrentHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentHandle
 * Method:    n_get_name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentHandle_n_1get_1name
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentHandle
 * Method:    n_set_sequential
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentHandle_n_1set_1sequential
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentHandle
 * Method:    n_set_upload_mode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentHandle_n_1set_1upload_1mode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentHandle
 * Method:    n_set_share_mode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentHandle_n_1set_1share_1mode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentHandle
 * Method:    n_set_priority
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentHandle_n_1set_1priority
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentHandle
 * Method:    n_is_valid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentHandle_n_1is_1valid
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentHandle
 * Method:    n_get_status
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentHandle_n_1get_1status
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentHandle
 * Method:    n_delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentHandle_n_1delete
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentHandle
 * Method:    n_num_files
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentHandle_n_1num_1files
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentHandle
 * Method:    n_file_at
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentHandle_n_1file_1at
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentHandle
 * Method:    n_rename_file
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentHandle_n_1rename_1file
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
