/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_danoeh_antennapod_bittorrent_TorrentStatus */

#ifndef _Included_de_danoeh_antennapod_bittorrent_TorrentStatus
#define _Included_de_danoeh_antennapod_bittorrent_TorrentStatus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_state
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1state
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_paused
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1paused
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_auto_managed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1auto_1managed
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_sequential_download
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1sequential_1download
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_seeding
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1seeding
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_finished
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1finished
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_progress
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1progress
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_total_download
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1total_1download
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_total_upload
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1total_1upload
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_download_rate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1download_1rate
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_upload_rate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1upload_1rate
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_total_done
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1total_1done
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_total_wanted_done
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1total_1wanted_1done
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_total_wanted
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1total_1wanted
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_TorrentStatus
 * Method:    n_delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_danoeh_antennapod_bittorrent_TorrentStatus_n_1delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
