/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_danoeh_antennapod_bittorrent_TorrentStatus_State */

#ifndef _Included_de_danoeh_antennapod_bittorrent_TorrentStatus_State
#define _Included_de_danoeh_antennapod_bittorrent_TorrentStatus_State
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
