/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_danoeh_antennapod_bittorrent_Session */

#ifndef _Included_de_danoeh_antennapod_bittorrent_Session
#define _Included_de_danoeh_antennapod_bittorrent_Session
#ifdef __cplusplus
extern "C" {
#endif
#undef de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_SEED_MODE
#define de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_SEED_MODE 1L
#undef de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_OVERRIDE_RESUME_DATA
#define de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_OVERRIDE_RESUME_DATA 2L
#undef de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_UPLOAD_MODE
#define de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_UPLOAD_MODE 4L
#undef de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_SHARE_MODE
#define de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_SHARE_MODE 8L
#undef de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_APPLY_IP_FILTER
#define de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_APPLY_IP_FILTER 16L
#undef de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_PAUSED
#define de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_PAUSED 32L
#undef de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_AUTO_MANAGED
#define de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_AUTO_MANAGED 64L
#undef de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_DUPLICATE_IS_ERROR
#define de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_DUPLICATE_IS_ERROR 128L
#undef de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_MERGE_RESUME_TRACKERS
#define de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_MERGE_RESUME_TRACKERS 256L
#undef de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_UPDATE_SUBSCRIBE
#define de_danoeh_antennapod_bittorrent_Session_ADD_TORRENT_UPDATE_SUBSCRIBE 512L
/*
 * Class:     de_danoeh_antennapod_bittorrent_Session
 * Method:    n_session
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_danoeh_antennapod_bittorrent_Session_n_1session
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_Session
 * Method:    n_listen_on
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_danoeh_antennapod_bittorrent_Session_n_1listen_1on
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_danoeh_antennapod_bittorrent_Session
 * Method:    n_add_torrent_url
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_de_danoeh_antennapod_bittorrent_Session_n_1add_1torrent_1url
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     de_danoeh_antennapod_bittorrent_Session
 * Method:    n_add_torrent_file
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_de_danoeh_antennapod_bittorrent_Session_n_1add_1torrent_1file
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     de_danoeh_antennapod_bittorrent_Session
 * Method:    n_remove_torrent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_danoeh_antennapod_bittorrent_Session_n_1remove_1torrent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_danoeh_antennapod_bittorrent_Session
 * Method:    n_get_torrents
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_de_danoeh_antennapod_bittorrent_Session_n_1get_1torrents
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_Session
 * Method:    n_shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_danoeh_antennapod_bittorrent_Session_n_1shutdown
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_Session
 * Method:    n_delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_danoeh_antennapod_bittorrent_Session_n_1delete
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_Session
 * Method:    n_pop_alert
 * Signature: ()Lde/danoeh/antennapod/bittorrent/Alert;
 */
JNIEXPORT jobject JNICALL Java_de_danoeh_antennapod_bittorrent_Session_n_1pop_1alert
  (JNIEnv *, jobject);

/*
 * Class:     de_danoeh_antennapod_bittorrent_Session
 * Method:    n_wait_for_alert
 * Signature: (J)Lde/danoeh/antennapod/bittorrent/Alert;
 */
JNIEXPORT jobject JNICALL Java_de_danoeh_antennapod_bittorrent_Session_n_1wait_1for_1alert
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
